config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
  get "search" => "searches#search"
end

app/views/layouts/_error_form.html.erb
<% if model.errors.any? %>
  <div id = "error_explanation">
    <h3>
      <%= model.errors.count %> errors prohibited this obj from being saved:
    </h3>

    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_new_book.html.erb
<h2 class="mt-3">New book</h2>

<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<div class="text-center">
    <% if user_signed_in? %>
        <div class="search_form">
            <%= form_with url:search_path, local: true, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                <%= f.submit "検索", class: "btn btn-outline-dark btn-light btn-sm" %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/layouts/_user_info.html.erb
<h2>User info</h2>

<p><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpeg" %></p>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-sm btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d903263f9b.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>

          <button class="navbar-toggler" type="button", data-toggle="collapse", data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>

              <% else %>
              <li class="nav-item">
                <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <main>
      <%= render "layouts/search" %>
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>